### ISSUE TITLE
文章组织——分类、Tag、归档与搜索

### ISSUE THREAD

**Issue by downgoon** [downgoon/mdblog#3]
参考资料： https://hexo.io/docs/front-matter

Setting | Description | Default
-- | -- | --
layout | Layout |  
title | Title |  
date | Published date | File created date
updated | Updated date | File updated date
comments | Enables comment feature for the post | true
tags | Tags (Not available for pages) |  
categories | Categories (Not available for pages) |  
permalink | Overrides the default permalink of the post |  

## 归档、分类与Tag

``` yml
---
title: 透过案例漫谈用户思维
date: 2019/06/28
categories:
- 方法论
- 产品
tags:
- 产品思维
- 物流
--- 
```

其中：
- ``date``:  表示文章的发表时间。如果没填，则按文件在操作系统上的创建时间为准。它是``Partition Key``，文章会按日期进行归档，按归档存储。
- ``categories``： 表示文章的分类。通常认为分类是一棵树，一篇文章有且只能属于一个分类，当然分类可以有层级，一级分类、二级分类、三级分类。所以上述的分类表示的是``方法论->产品``两个层级。但是内容运营过程中，发现分类还可以有很多``维度``，不同的维度，可以有不同的分类。也就是说，一篇文章，站在不同的维度，可以有多个分类。Hexo能否支持呢？可以的，稍后给出样例。
- ``tags``:  给文章打标签。是一种自由的，可任意拓展的倒排检索方式。

### 支持多维度分类

``` yml
---
title: 透过案例漫谈用户思维
date: 2019/06/28
categories:
- [方法论, 产品]
- [产地, 中国, 北京]
- [语言, 中文]
tags:
- 产品思维
- 物流
--- 
```

### 归档、分类与Tag

![image](https://user-images.githubusercontent.com/23731186/60824876-0aa5e780-a1dd-11e9-8f1d-85c87d89f516.png)

## 搜索

![image](https://user-images.githubusercontent.com/23731186/60825202-c23af980-a1dd-11e9-9714-69507b6ae99e.png)
