### ISSUE TITLE
文章链接如何生成？ID？文件名？按年归档？

### ISSUE THREAD

**Issue by downgoon** [downgoon/mdblog#4]
参考资料：https://hexo.io/docs/permalinks

![image](https://user-images.githubusercontent.com/23731186/60826033-9de01c80-a1df-11e9-9036-cfa197414287.png)

``` yml
# permalink: :year/:month/:day/:title/
# permalink: :title/
permalink: :year/:month/:title/
permalink_defaults:
```

文章的持久URL地址，推荐用按月归档的方式，这样一个目录下，不至于太多文章，减少目录的``inode``数量。
